import libs         = cuda-nvcc%lib{nvcc}
import bin2c        = cuda-nvcc%exe{bin2c}
import cudafe       = cuda-nvcc%exe{cudafe++}
import fatbinary    = cuda-nvcc%exe{fatbinary}
import nvcc         = cuda-nvcc%exe{nvcc}
import nvlink       = cuda-nvcc%exe{nvlink}
import ptxas        = cuda-nvcc%exe{ptxas}
import device_query = cuda-nvcc%exe{__nvcc_device_query}

testscript{bin2c}@./:         test = $bin2c
testscript{cudafe}@./:        test = $cudafe
testscript{fatbinary}@./:     test = $fatbinary
testscript{nvcc}@./:          test = $nvcc
testscript{nvlink}@./:        test = $nvlink
testscript{ptxas}@./:         test = $ptxas
testscript{device_query}@./:  test = $device_query

./: testscript{bin2c}@./        $bin2c
./: testscript{cudafe}@./       $cudafe
./: testscript{fatbinary}@./    $fatbinary
./: testscript{nvcc}@./         $nvcc
./: testscript{nvlink}@./       $nvlink
./: testscript{ptxas}@./        $ptxas
./: testscript{device_query}@./ $device_query

./: exe{driver}: {c}{**} $libs
