define [see_through] import: group

name = $string.replace($project, 'cuda-', '')

source redist.build

json{$name-manifest}: $src_root/manifest manifest.json

manifest_json = [json_object] $json.load($src_base/manifest.json)
package_ver   = "$(version.major).$(version.minor).$(version.patch)"

pub_hdrs = [strings]
for d: [json_array] ($manifest_json["includeDirs"])
{
  dir = [string] $d
  pub_hdrs += "-I$out_base/$dir"
}

for plat: [json_object] ($manifest_json["platforms"])
{
  plat_key = $member_name($plat)
  plat_val = $member_value($plat)
  enabled  = [bool] ($cc.target.cpu-$cc.target.class == $plat_key)
  platform = [string] ($plat_val["platform"])
  archive{$name-$platform-$package_ver}: json{$name-manifest} manifest.json: include = $enabled
  extract{$name}: archive{$name-$platform-$package_ver}: include = $enabled
}

import{$name-headers}: extract{$name}: update = match
import{$name-legals}:  extract{$name}: update = match

import{$name-legals}:
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files

  legal = [path] "$out_base/LICENSE"

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'imported files' \
    --target-default-type 'legal' \
    --format lines \
    --file $d \
    -- \
      echo $legal >$d

  diag import $>

  for t : $filter_out($>, group)
  {
    touch $path($t)
  }
}}

import{$name-headers}:
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files

  find "$out_base/include/" -type f -name "*" \
    | set -n f [paths]

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'headers' \
    --target-default-type 'h' \
    --target-extension-type '=h' \
    --target-extension-type 'hpp=hxx' \
    --target-extension-type 'cuh=hxx' \
    --target-extension-type 'inl=hxx' \
    --format lines \
    -- echo $regex.merge($f, '(.+)', '\1\n')

  diag import $>

  for f : $filter($>, h hxx)
  {
    touch $path($f)
  }
}}

./: json{package}
json = [json_object] $json.load($src_base/package.json)
for plat: [json_object] ($json["platforms"])
{
  plat_key = $member_name($plat)
  enabled  = [bool] ($cc.target.cpu-$cc.target.class == $plat_key)
  for m: [json_object] ($member_value($plat))
  {
    n = $member_name($m)

    ./: lib{$n}:
    {
      include = $enabled
      clean   = false
    }
    [rule_hint=cxx] \
    lib{$n}: import{$name-legals} import{$name-headers}: \
             extract{$name}:
    {
      include = $enabled
      update  = match
    }

    lib{$n}:
    {
      cc.type            = cc
      cc.export.poptions = $pub_hdrs
    }
  }
}

lib/liba{**}: install = false

include/h{**}:
{
  install         = include/$project/
  install.subdirs = true
}
