import libs = libnvcc%liba{nvcc}

# make sure executables are importable
import! all = \
  libnvcc%exe{bin2c} \
  libnvcc%exe{cudafe++} \
  libnvcc%exe{fatbinary} \
  libnvcc%exe{nvcc} \
  libnvcc%exe{nvlink} \
  libnvcc%exe{ptxas}

exe{driver}: {c}{**} $libs testscript{**} $all

c.loptions += -NODEFAULTLIB:LIBCMT
