import intf_libs = \
  cuda-nvcc%lib{nvcc} \
  cuda-nvrtc%libs{nvrtc}

name = $regex.replace($project, 'cuda-', '')

source redist.build
define [see_through] import: group

./: lib{$name}: import{legal} import{$name-headers} $intf_libs

redist{cuda_$name}: $src_root/manifest
archive{$cc.target.class-$cc.target.cpu-$version-archive.tar}: redist{cuda_$name}
extract{archive}: archive{$cc.target.class-$cc.target.cpu-$version-archive.tar}
import{legal}: extract{archive}: update = match
import{$name-headers}: extract{archive}: update = match

import{legal}:
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files

  legal = [path] "$out_base/LICENSE"

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'imported files' \
    --target-default-type 'legal' \
    --format lines \
    --file $d \
    -- \
      echo $legal >$d

  diag import $>

  for t : $filter_out($>, group)
    touch $path($t)
  end
}}

import{$name-headers}:
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files

  find "$out_base/include/" -type f -name "*" \
    | set -n f [paths]

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'headers' \
    --target-default-type 'hxx' \
    --target-extension-type '=h' \
    --target-extension-type 'h=hxx' \
    --target-extension-type 'hpp=hxx' \
    --target-extension-type 'inl=hxx' \
    --target-extension-type 'cuh=hxx' \
    --format lines \
    -- echo $regex.merge($f, '(.+)', '\1\n')

  diag import $>

  for f : $filter($>, h hxx)
    touch $path($f)
  end
}}

# Export options.

lib{$name}:
{
  cc.type = cxx
  cc.export.poptions = "-I$out_base/include" "-I$out_base/include/cccl"
  cc.export.libs = $intf_libs
}

lib/liba{**}: install = false

exe{*}:
{
  install         = bin/
}

include/hxx{*}:
{
  install         = include/$project/
  install.subdirs = true
}
