intf_libs =

name = $regex.replace($project, 'lib', '')

source redist.build
define [see_through] import: group

./: libs{$name}: import{legal} import{$name} import{$name-headers} $intf_libs

redist{lib$name}: $src_root/manifest
archive{$cc.target.class-$cc.target.cpu-$version-archive.tar}: redist{lib$name}
extract{archive}: archive{$cc.target.class-$cc.target.cpu-$version-archive.tar}
import{legal}: extract{archive}: update = match
import{$name}: extract{archive}: update = match
import{$name-headers}: extract{archive}: update = match

import{legal}:
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files

  legal = [path] "$out_base/LICENSE"

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'imported files' \
    --target-default-type 'legal' \
    --format lines \
    --file $d \
    -- \
      echo $legal >$d

  diag import $>

  for t : $filter_out($>, group)
    touch $path($t)
  end
}}

import{$name}:
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files

  find "$out_base/nvvm/bin/" -type f -name "*" \
    | set -n l [paths]
  l = $regex.filter_out_search($l, '.*cicc.*')
  find "$out_base/nvvm/lib/" -type f -name "*" \
    | set -n i [paths]
  i = $regex.filter_out_search($i, '.*static.*')

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'imported files' \
    --target-extension-type 'so=libs' \
    --target-extension-type 'dylib=libs' \
    --target-extension-type 'dll=libs' \
    --target-extension-type 'lib=libi' \
    --format lines \
    --file $d \
    -- \
      echo $regex.merge($l $i, '(.+)', '\1\n') >$d

  diag import $>

  for t : $filter_out($>, group)
    touch $path($t)
  end
}}

import{$name-headers}:
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files

  find "$out_base/nvvm/include/" -type f -name "*" \
    | set -n f [paths]

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'headers' \
    --target-default-type 'h' \
    --target-extension-type '=h' \
    --format lines \
    -- echo $regex.merge($f, '(.+)', '\1\n')

  diag import $>

  for f : $filter($>, h)
    touch $path($f)
  end
}}

## create phony libs{<name>} such that we can export a
#  deterministic libs{} target, and generate a single
#  libi{<name>} from all extracted import libraries.
<libs{$(name).dll} libi{$(name).dll.lib}>:
{{
  n     = $name($>[0])
  ilibs = ($filter($<, libi))

  $effect($bin.ld.path) -DUMP -NOLOGO -HEADERS $path($ilibs[0]) \
   | sed -n -e 's/.*machine \((.*)\)/\1/p' \
   | set -w m
  m = ($m[0])

  diag $name($bin.ar.path) $ilibs $>

  # create a dummy libs{<name>} as this is only acting as
  # an 'alias' target, essentially creating a phony lib.
  touch "$path($>[0])"

  # combine all import libraries to one
  $effect($bin.ar.path) -NOLOGO "-OUT:$path($>[1])" \
                        "-NAME:$n" "-MACHINE:$m" $path($ilibs) >! 2>&1
}}


if ($cc.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

## import exe{<name>} targets
# 
./: bin/exe{*}
<bin/exe{cicc.exe}>: extract{archive} fsdir{bin}
{{
  o = $directory($>[0])
  d = $o/$name($>[0]).files
  e = $filter($<, exe)

  find "$out_base/bin" -type f -name "*\.exe" \
    | set e [path]

  depdb dyndep \
    --dyn-target \
    --target-cwd "$o" \
    --target-what 'imported executables' \
    --target-default-type 'exe' \
    --target-extension-type '=exe' \
    --target-extension-type 'exe=exe' \
    --format lines \
    -- \
      echo $regex.merge($e, '(.+)', '\1\n')

  diag import ($>)
  for t : $filter_out($>, group)
    touch $path($t)
  end
}}

# Export options.

lib{$name}:
{
  cc.type = cc
  cc.export.poptions = "-I$out_base/nvvm/include"
  cc.export.libs = $intf_libs
}

# TODO: Handle shared lib installation.
#       Specifically don't install the "alias" lib
#       that just symlinks the real one. Only
#       install the latter & fix pkg-config targets.

exe{*}:
{
  install         = bin/
  install.subdirs = true
}

nvvm/include/h{*}:
{
  install         = include/$project/
  install.subdirs = true
}
